config/routes.rb
Rails.application.routes.draw do
  root to: "pages#home"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
  resources :chats, only: [:new, :create, :show] do
    resources :messages, only: [:new, :create]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/chat.rb
class Chat < ApplicationRecord
  has_many :messages, dependent: :destroy
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :chat
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/chats_controller.rb
class ChatsController < ApplicationController

  # def index
  #   @chat = Chat.find(param[:chat_id])
  #   # @chats =  current_user.chats.where(challenge: @challenge)
  #   @message = Message.new
  # end


  def show
    @chat = Chat.find(params[:id])
    # @chat = Chat.includes(:messages).find(params[:id])
    if Rails.env.development?
      @input_tokens = @chat.messages.pluck(:input_tokens).compact.sum
      @output_tokens = @chat.messages.pluck(:output_tokens).compact.sum
      @context_window = RubyLLM.models.find(@chat.model_id).context_window
    end
    @message = Message.new
  end

  def create
    @chat = Chat.new(chat_title: Date.today.to_s , model_id: "gpt-4.1-nano")
    if @chat.save
      redirect_to chat_path(@chat)
    else
      render :new, status: :unprocessable_entity
    end
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  before_action :set_chat, only: %i[new create]


  SYSTEM_PROMPT = <<~PROMPT
    You are a Sommelier.

    I am a person looking for wine recommendations or general information.

    Give me the name, region, vintage, grape type, and taste profile.

    Answer consicely with bullet points in markdown.

  PROMPT

  def new
    # @chat = Chat.find(params[:chat_id])
    @message = Message.new
  end

  def create
    @message = Message.new(message_params)
    @chat = Chat.find(params[:chat_id])
    @message.chat = @chat
    @message.role = "user"
    if @message.save
      @response = RubyLLM.chat.with_instructions(SYSTEM_PROMPT).ask(@message.content)
      Message.create(role: "Maître Sommelier", content: @response.content, chat: @chat)
      redirect_to chat_path(@chat)
    else
      render :new, status: :unprocessable_entity
    end
  end

  private

  # def instructions
  #   [SYSTEM_PROMPT, @chat.challenge.system_prompt].compact.join("\n\n")
  # end

  def set_chat
    @chat = Chat.find(params[:chat_id])
  end

  def message_params
    params.require(:message).permit(:content)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
    @chat = Chat.new
  end

  def chat
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/chats/index.html.erb
<%# <h1>Chats for <%= @chat.chat_title %>

<%# <div class="mb-4"> %>
  <%# <% if @chats.any? %>
    <%# <ul> %>
      <%# <% @chats.each do |chat| %>
        <%# <li><%= link_to chat.chat_title, chat_path(chat) %>
      <%# <% end %>
    <%# </ul> %>
  <%# <% else %>
    <%# There are no chats yet. %>
  <%# <% end %>
<%# </div> %>

<%# <%= simple_form_for [@challenge, @chat] do |f| %>
  <%# <%= f.button :submit, "New chat", class: "btn btn-primary" %>
<%# <% end %>

app/views/chats/new.html.erb
<h1>hello from chat new</h1>

<h1>New Chat</h1>
<%= simple_form_for @chat do |f| %>
  <%= f.input :chat_title %>
  <%= f.submit "Chat", class: "btn btn-primary" %>
<% end %>

app/views/chats/show.html.erb
<% show_banner_img = 'https://images.pexels.com/photos/5847674/pexels-photo-5847674.jpeg' %>
<%= render "shared/banner", h1: "Wine-O-Bot", p: "Please ask your personnal sommelier for a recommendation.", image_url: show_banner_img %>

<div>
  <h1>Welcome, how can I help?</h1>
  <% if Rails.env.development? %>
  <span class="float-end">
    <%# Input tokens:  @input_tokens  / Output tokens:  @output_tokens/ Context window:  @context_window  %>
  </span>
  <% end %>
</div>

<div class="chat-header mb-4">
  <% if Rails.env.development? %>
    <span class="float-end text-muted small">
      <%# Input tokens: @input_tokens / Output tokens: @output_tokens / Context window: @context_window %>
    </span>
  <% end %>
</div>

<div class="new-message-form mb-4">
  <%= simple_form_for [@chat, @message] do |f| %>
    <%= f.input :content, placeholder: "Ask your Sommelier something..." %>
    <%= f.submit "Send message", class: "btn btn-global" %>
  <% end %>
</div>

<div class="chat-messages d-flex flex-column">
  <% @chat.messages.order(:created_at).each do |message| %>
    <div class="d-flex mb-3 <%= message.role.downcase == 'user' ? 'justify-content-start' : 'justify-content-end' %>">
      <div class="p-2 rounded" style="background-color: #F5F5DC; max-width: 60%;">
        <strong><%= message.role %>:</strong>
        <div>
          <%= simple_format(message.content.gsub('**', '')) %>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>WineExperience</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
   <%= render "shared/navbar" %>

    <%= yield %>

  </body>

</html>

app/views/pages/home.html.erb
<% home_banner_img = 'https://media.istockphoto.com/id/991732782/photo/close-up-of-sommelier-serving-red-wine-at-fine-dining-restaurant.jpg?s=612x612&w=0&k=20&c=KPTJbmK7ryWZczvKJXkvCiwtc_BcX0oqJJN91qG2yVw=' %>
<%= render "shared/banner", h1: "Wine Experience", p: "The Wine-O-Bot is your personnal AI Sommelier.", image_url: home_banner_img %>
<div class="Options-Container">

  <div class="Option-Card" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(https://raw.githubusercontent.com/lewagon/fullstack-images/master/uikit/dinner.jpg)">

    <%= simple_form_for @chat do |f| %>
      <%= f.submit "Open Chat with Chatbot", class: "btn btn-warning" %>
    <% end %>

  </div>

  <div class="Option-Card" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(https://raw.githubusercontent.com/lewagon/fullstack-images/master/uikit/lunch.jpg)">
    <h1>

    <%= simple_form_for @chat do |f| %>
      <%= f.submit "View History", class: "btn btn-warning" %>
    <% end %>

    </h1>
  </div>


</div>

app/views/shared/_banner.html.erb
<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(<%= local_assigns[:image_url] %>);">
  <div class="container">
    <h1><%= local_assigns[:h1] %></h1>
    <p><%= local_assigns[:p] %></p>
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <div class="container-fluid">
    <%= link_to root_path, class: "navbar-brand" do %>
      <p>  <i class="fa-solid fa-wine-bottle"></i></p>
    <% end %>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
        <%# if user_signed_in? %>
          <li class="nav-item active">
            <%= link_to "Home", root_path, class: "nav-link" %>
          </li>
          <li class="nav-item dropdown">
            <%= image_tag "https://kitt.lewagon.com/placeholder/users/ssaunier", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { bs_toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
            <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
              <%= link_to "History", chats_path, class: "dropdown-item" %>
              <%= link_to "Log out", "#", class: "dropdown-item", data: {turbo_method: :delete} %>
              <%# link_to "Log out", destroy_user_session_path, class: "dropdown-item", data: {turbo_method: :delete} %>
            </div>
          </li>
        <%# else %>
          <!--li class="nav-item"-->
            <%#= link_to "Login", new_user_session_path, class: "nav-link" %>
          <!--/li-->
        <%# end %>
      </ul>
    </div>
  </div>
</div>

app/views/shared/_sidenav.html.erb
<ul class="position-sticky sticky-top nav flex-column">
  <li class="nav-item">
    <%= link_to "#", class: "nav-link text-dark", data: { action: "click->toggle#call" } do %>
      <i class="fa-regular fa-square-caret-left"></i>
    <% end %>
  </li>

</ul>